# Generated by Django 2.2.8 on 2020-10-08 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('source', models.CharField(max_length=200, verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.Research', verbose_name='Исследование')),
            ],
            options={
                'verbose_name': 'Аналитика',
                'verbose_name_plural': 'Аналитика',
            },
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to='images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.Post')),
            ],
            options={
                'verbose_name': 'Изображение для окна аналитики',
                'verbose_name_plural': 'Изображения для окна аналитики',
            },
        ),
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(blank=True, null=True, upload_to='images')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.Info')),
            ],
            options={
                'verbose_name': 'Изображение для окна о нас',
                'verbose_name_plural': 'Изображения для окна о нас',
            },
        ),
    ]
