# Generated by Django 2.2.8 on 2020-10-13 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.Research', verbose_name='Исследование'),
        ),
        migrations.AddField(
            model_name='imagepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.Post'),
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='post.Info'),
        ),
    ]
