# Generated by Django 3.1.1 on 2020-10-07 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0016_research_similars'),
        ('post', '0002_auto_20201004_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.CharField(default='default', max_length=200, verbose_name='Источник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='research',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='research.research', verbose_name='Исследование'),
            preserve_default=False,
        ),
    ]