# Generated by Django 3.1.1 on 2020-10-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201007_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='header',
            new_name='name',
        ),
    ]
