# Generated by Django 2.2.8 on 2020-10-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201007_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='description_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='description_ky',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='description_ru',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='header_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='info',
            name='header_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='info',
            name='header_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.CharField(max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ky',
            field=models.CharField(max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.CharField(max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='description_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='description_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='description_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='header_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='header_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='header_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
