# Generated by Django 3.1.1 on 2020-09-23 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 9, 23, 13, 46, 54, 677880, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
