# Generated by Django 3.1.1 on 2020-09-28 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_research_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': 'Исследование', 'verbose_name_plural': 'Исследования'},
        ),
        migrations.AlterField(
            model_name='research',
            name='status',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='research.status'),
        ),
    ]
