# Generated by Django 3.1.1 on 2020-10-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0013_auto_20201001_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='country',
            field=models.ManyToManyField(to='research.Country', verbose_name='Страна'),
        ),
    ]
