# Generated by Django 3.1.1 on 2020-10-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_research_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='research',
            name='country',
            field=models.ManyToManyField(null=True, to='research.Country', verbose_name='Страна'),
        ),
    ]
