# Generated by Django 3.1.1 on 2020-10-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('name_of_organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название организации')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('extra', models.CharField(max_length=255, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('description', models.CharField(max_length=1000, verbose_name='Информация о партнерстве')),
            ],
            options={
                'verbose_name': 'Партнерство',
                'verbose_name_plural': 'Партнерство',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=300, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'ЧАВО',
                'verbose_name_plural': 'ЧАВО',
            },
        ),
    ]
