# Generated by Django 2.2.8 on 2020-10-16 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('name_of_organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название организации')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('extra', models.CharField(max_length=255, verbose_name='Дополнительно')),
            ],
            options={
                'verbose_name': 'Обратная связь(партнерство)',
                'verbose_name_plural': 'Обратная связь(партнерство)',
            },
        ),
        migrations.CreateModel(
            name='HaveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('name_of_organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название организации')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('extra', models.CharField(max_length=255, verbose_name='Ваш вопрос')),
            ],
            options={
                'verbose_name': 'Обратная связь(вопросы)',
                'verbose_name_plural': 'Обратная связь(вопросы)',
            },
        ),
        migrations.CreateModel(
            name='PartnershipInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Информация о партнерстве',
                'verbose_name_plural': 'Информация о партнерстве',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('question_ru', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('question_ky', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('question_en', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=300, verbose_name='Ответ')),
                ('answer_ru', models.CharField(max_length=300, null=True, verbose_name='Ответ')),
                ('answer_ky', models.CharField(max_length=300, null=True, verbose_name='Ответ')),
                ('answer_en', models.CharField(max_length=300, null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'ЧАВО',
                'verbose_name_plural': 'ЧАВО',
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('header_ru', models.CharField(max_length=1000, null=True, verbose_name='Заголовок')),
                ('header_ky', models.CharField(max_length=1000, null=True, verbose_name='Заголовок')),
                ('header_en', models.CharField(max_length=1000, null=True, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=1000, verbose_name='Информация о партнерстве')),
                ('description_ru', models.CharField(max_length=1000, null=True, verbose_name='Информация о партнерстве')),
                ('description_ky', models.CharField(max_length=1000, null=True, verbose_name='Информация о партнерстве')),
                ('description_en', models.CharField(max_length=1000, null=True, verbose_name='Информация о партнерстве')),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership', to='question.PartnershipInfo')),
            ],
            options={
                'verbose_name': 'Партнерство',
                'verbose_name_plural': 'Партнерство',
            },
        ),
    ]