# Generated by Django 2.2.8 on 2020-10-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('name_of_organization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название организации')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('email', models.CharField(max_length=255, verbose_name='Почта')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('extra', models.CharField(max_length=255, verbose_name='Ваш вопрос')),
            ],
            options={
                'verbose_name': 'Обратная связь(вопросы)',
                'verbose_name_plural': 'Обратная связь(вопросы)',
            },
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
