# Generated by Django 2.2.8 on 2020-10-14 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20201014_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='havequestion',
            name='position',
        ),
    ]
