# Generated by Django 2.2.8 on 2020-10-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20201015_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='image',
        ),
        migrations.AddField(
            model_name='partnership',
            name='header',
            field=models.CharField(default='test', max_length=1000, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
