# Generated by Django 2.2.8 on 2020-10-16 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='MobApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('description_ru', models.CharField(max_length=1000, null=True, verbose_name='Описание')),
                ('description_ky', models.CharField(max_length=1000, null=True, verbose_name='Описание')),
                ('description_en', models.CharField(max_length=1000, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение')),
                ('url', models.URLField(max_length=250, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Раздел о моб. приложении',
                'verbose_name_plural': 'Раздел о моб. приложении',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MobApp', verbose_name='Информация о мобильном приложении')),
                ('сontacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ContactInfo', verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=255, verbose_name='Данные')),
                ('contactInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='main.ContactInfo')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
    ]