# Generated by Django 2.2.8 on 2020-10-08 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='Номер')),
                ('email', models.CharField(max_length=30, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='MobApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение')),
                ('url', models.URLField(max_length=250, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Раздел о моб. приложении',
                'verbose_name_plural': 'Раздел о моб. приложении',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Info', verbose_name='О нас')),
                ('analytic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post', verbose_name='Информация об аналитике')),
                ('categories', models.ManyToManyField(to='research.Category', verbose_name='Категории')),
                ('mob_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MobApp', verbose_name='Информация о мобильном приложении')),
                ('news', models.ManyToManyField(to='post.News', verbose_name='Новости')),
                ('сontacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ContactInfo', verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
    ]
