# Generated by Django 3.1.1 on 2020-10-06 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0002_auto_20201004_1423'),
        ('research', '0016_research_similars'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.info')),
                ('analytic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('categories', models.ManyToManyField(to='research.Category', verbose_name='Категории')),
                ('news', models.ManyToManyField(to='post.News', verbose_name='Новости')),
            ],
        ),
    ]
