# Generated by Django 2.2.16 on 2020-10-20 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20201020_0634'),
        ('post', '0002_auto_20201020_0634'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='category',
            field=models.ManyToManyField(to='research.Category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobapp',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mobapp',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mobapp',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mobapp',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
