# Generated by Django 2.2.16 on 2020-10-27 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201020_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post', verbose_name='Блог'),
        ),
    ]
