# Generated by Django 3.1.1 on 2020-10-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201006_2340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobailInfo',
        ),
    ]
