# Generated by Django 3.1.1 on 2020-10-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_mobailinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение')),
                ('url', models.URLField(max_length=250)),
            ],
            options={
                'verbose_name': 'Информация о мобильном прижении',
                'verbose_name_plural': 'Информация о мобильном прижении',
            },
        ),
        migrations.AddField(
            model_name='mainpage',
            name='mob_app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.mobapp'),
            preserve_default=False,
        ),
    ]
