# Generated by Django 3.1.1 on 2020-10-06 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201006_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.AlterModelOptions(
            name='mobapp',
            options={'verbose_name': 'Раздел о моб. прижении', 'verbose_name_plural': 'Раздел о моб. прижении'},
        ),
        migrations.AddField(
            model_name='mainpage',
            name='сontacts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.contactinfo'),
            preserve_default=False,
        ),
    ]
