# Generated by Django 3.1.1 on 2020-10-07 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201004_1423'),
        ('main', '0005_auto_20201007_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobapp',
            options={'verbose_name': 'Раздел о моб. приложении', 'verbose_name_plural': 'Раздел о моб. приложении'},
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.CharField(max_length=30, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='number',
            field=models.CharField(max_length=15, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='about_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.info', verbose_name='О нас'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='analytic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='Информация об аналитике'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='mob_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mobapp', verbose_name='Информация о мобильном приложении'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='сontacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contactinfo', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='mobapp',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mobapp',
            name='url',
            field=models.URLField(max_length=250, verbose_name='Ссылка'),
        ),
    ]
