# Generated by Django 3.1.1 on 2020-10-09 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201009_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='analytic',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='news',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contactInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='main.contactinfo'),
        ),
    ]
