# Generated by Django 2.2.8 on 2020-10-14 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='info',
            new_name='name',
        ),
    ]
