# Generated by Django 2.2.8 on 2020-10-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201015_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='info',
        ),
    ]
