# Generated by Django 2.2.8 on 2020-10-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201015_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobapp',
            name='description_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='mobapp',
            name='description_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='mobapp',
            name='description_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Описание'),
        ),
    ]
