# Generated by Django 2.2.8 on 2020-10-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201015_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobapp',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mobapp',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mobapp',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mobapp',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
