# Generated by Django 2.2.8 on 2020-10-19 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20201019_2215'),
        ('research', '0025_auto_20201019_2215'),
        ('main', '0013_auto_20201019_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='research.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpage',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
            preserve_default=False,
        ),
    ]
