# Generated by Django 2.2.8 on 2020-10-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0025_auto_20201019_2215'),
        ('main', '0014_auto_20201019_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='category',
        ),
        migrations.AddField(
            model_name='mainpage',
            name='category',
            field=models.ManyToManyField(to='research.Category', verbose_name='Категории'),
        ),
    ]
