# Generated by Django 2.2.8 on 2020-10-25 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201019_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post', verbose_name='Блог'),
        ),
    ]
