# Generated by Django 2.2.8 on 2020-10-28 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_mainpage_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobapp',
            name='header',
            field=models.CharField(default='text', max_length=255, verbose_name='Оглавнение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Info', verbose_name='О нас'),
        ),
    ]
