# Generated by Django 2.2.8 on 2020-09-28 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qadmins',
            name='admin_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='initial_reference', to=settings.AUTH_USER_MODEL),
        ),
    ]
