# Generated by Django 2.2.16 on 2020-10-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qadmins',
            name='about_me',
            field=models.TextField(default='lalalala', max_length=2000),
            preserve_default=False,
        ),
    ]
