# Generated by Django 2.2.8 on 2020-09-30 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200928_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ФИО', max_length=120, verbose_name='ФИО')),
                ('logo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название организации')),
                ('email', models.EmailField(max_length=120, unique=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(default=0, max_length=20, verbose_name='Номер телефона')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(default=0, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_reference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
    ]
