# Generated by Django 2.2.8 on 2020-10-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20201008_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='surname',
            field=models.CharField(default='ФИО', max_length=120, verbose_name=' Фамилия'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default='ФИО', max_length=120, verbose_name=' Имя'),
        ),
    ]
