# Generated by Django 2.2.8 on 2020-10-05 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20201005_0844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
