# Generated by Django 2.2.8 on 2020-10-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_delete_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный пользователь'),
        ),
    ]
