# Generated by Django 2.2.8 on 2020-10-08 10:20

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='research.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Ключевое слово')),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключевые слова',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('pages', models.IntegerField(verbose_name='Количество страниц')),
                ('old_price', models.IntegerField(verbose_name='Старая цена')),
                ('new_price', models.IntegerField(verbose_name='Новая цена')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('demo', models.FileField(blank=True, null=True, upload_to='demos', verbose_name='Демоверсия')),
                ('research', models.FileField(blank=True, null=True, upload_to='', verbose_name='Исследование')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.Category', verbose_name='Категория')),
                ('country', models.ManyToManyField(null=True, to='research.Country', verbose_name='Страна')),
                ('hashtag', models.ManyToManyField(to='research.Hashtag', verbose_name='Ключевые слова')),
                ('similars', models.ManyToManyField(blank=True, null=True, related_name='_research_similars_+', to='research.Research', verbose_name='Похожие исследования')),
                ('status', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='research.Status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
            },
        ),
    ]
