# Generated by Django 3.1.1 on 2020-09-28 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20200927_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='research',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.status'),
        ),
    ]
