# Generated by Django 2.2.8 on 2020-10-08 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_research_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='author',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='registration.QAdmins'),
        ),
    ]
