# Generated by Django 3.1.1 on 2020-09-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_auto_20200928_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='demo',
            field=models.FileField(blank=True, null=True, upload_to='demos'),
        ),
        migrations.AlterField(
            model_name='research',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
