# Generated by Django 3.1.1 on 2020-09-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_auto_20200928_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='research',
        ),
        migrations.AddField(
            model_name='research',
            name='hashtag',
            field=models.ManyToManyField(to='research.Hashtag'),
        ),
    ]
