# Generated by Django 3.1.1 on 2020-09-30 18:44

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_auto_20200928_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Ключевое слово')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name': 'Ключевое слово', 'verbose_name_plural': 'Ключевые слова'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='research.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Ключевое слово'),
        ),
        migrations.AlterField(
            model_name='research',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='research',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='research',
            name='demo',
            field=models.FileField(blank=True, null=True, upload_to='demos', verbose_name='Демоверсия'),
        ),
        migrations.AlterField(
            model_name='research',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='research',
            name='hashtag',
            field=models.ManyToManyField(to='research.Hashtag', verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='research',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='research',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='research',
            name='new_price',
            field=models.IntegerField(verbose_name='Новая цена'),
        ),
        migrations.AlterField(
            model_name='research',
            name='old_price',
            field=models.IntegerField(verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='research',
            name='pages',
            field=models.IntegerField(verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='research',
            name='research',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Исследование'),
        ),
        migrations.AlterField(
            model_name='research',
            name='status',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='research.status', verbose_name='Статус'),
        ),
    ]
