# Generated by Django 3.1.1 on 2020-10-04 14:23

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('research', '0015_auto_20201002_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
