# Generated by Django 2.2.8 on 2020-10-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0016_research_similars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='country',
            field=models.ManyToManyField(null=True, related_name='country', to='research.Country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='research',
            name='hashtag',
            field=models.ManyToManyField(related_name='hashtag', to='research.Hashtag', verbose_name='Ключевые слова'),
        ),
    ]
