# Generated by Django 2.2.8 on 2020-10-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0017_auto_20201010_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='country',
            field=models.ManyToManyField(null=True, to='research.Country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='research',
            name='hashtag',
            field=models.ManyToManyField(to='research.Hashtag', verbose_name='Ключевые слова'),
        ),
    ]
