# Generated by Django 2.2.8 on 2020-10-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0018_auto_20201012_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images', verbose_name='Изображение'),
        ),
    ]
