# Generated by Django 2.2.8 on 2020-10-14 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0020_auto_20201013_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_ru',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='research',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='research',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='research',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='research',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='status',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='status',
            name='name_ru',
        ),
    ]
