# Generated by Django 2.2.8 on 2020-10-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0022_auto_20201015_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_ky',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_ru',
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name_ky',
            field=models.CharField(max_length=1000, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Статус'),
        ),
    ]
