# Generated by Django 2.2.8 on 2020-10-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ФИО', max_length=120, verbose_name='ФИО')),
                ('logo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название организации')),
                ('email', models.EmailField(max_length=120, unique=True, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(default=0, max_length=20, verbose_name='Номер телефона')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Форма заказа',
                'verbose_name_plural': 'Формы заказов',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
