# Generated by Django 2.2.16 on 2020-10-20 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0002_auto_20201020_0634'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_items', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('total_of_all', models.IntegerField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('ordered_item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='research.Research')),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='ordered_researches',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total',
        ),
        migrations.CreateModel(
            name='ItemsInCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_in_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_for_sell', to='orders.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='DemoVersionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ФИО', max_length=120, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=120, verbose_name='Электронная почта')),
                ('phone_number', models.CharField(default=0, max_length=20, verbose_name='Номер телефона')),
                ('desired_research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanted_research', to='research.Research')),
            ],
            options={
                'verbose_name': 'Форма демоверсии',
                'verbose_name_plural': 'Формы демоверсий',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='items_ordered',
            field=models.ManyToManyField(related_name='items_to_pay', to='orders.Cart'),
        ),
    ]
