# Generated by Django 2.2.8 on 2020-10-07 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0016_research_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderform',
            options={'verbose_name': 'Форма заказа', 'verbose_name_plural': 'Формы заказов'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='orders',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='who_buys',
        ),
        migrations.AddField(
            model_name='orders',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='ordered_researches',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='researches', to='research.Research'),
        ),
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
