# Generated by Django 2.2.8 on 2020-10-16 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201016_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='ordered_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='research.Research'),
        ),
    ]
