# Generated by Django 2.2.16 on 2020-10-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201020_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortDescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(upload_to='')),
                ('text1', models.TextField()),
                ('picture2', models.ImageField(upload_to='')),
                ('text2', models.TextField()),
            ],
            options={
                'verbose_name': 'Краткое описание',
                'verbose_name_plural': 'Краткие описания',
            },
        ),
    ]
