# Generated by Django 2.2.8 on 2020-10-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201008_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderform',
            name='email',
            field=models.EmailField(max_length=120, verbose_name='Электронная почта'),
        ),
    ]
