# Generated by Django 2.2.8 on 2020-10-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201008_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderform',
            name='surname',
            field=models.CharField(default='ФИО', max_length=120, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='name',
            field=models.CharField(default='ФИО', max_length=120, verbose_name='Имя'),
        ),
    ]
