# Generated by Django 2.2.16 on 2020-10-26 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_qadmins_about_me'),
        ('orders', '0003_shortdescriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_downloaded', models.IntegerField()),
                ('watches', models.IntegerField()),
                ('bought', models.IntegerField()),
                ('partner_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_admin', to='registration.QAdmins')),
            ],
        ),
    ]
